### ISSUE TITLE
configobj.ConfigObjError: Parsing failed with several errors.

### ISSUE THREAD

**Issue by tinkhaven** [nix-community/pip2nix#18]
Hi

I was trying out your package but ran into this error. The requirements.txt I'm trying to parse is the one from odoo (https://github.com/odoo/odoo/tree/8.0).

I will try to dig in a bit myself but maybe you have a quick clue?

```
$ pip2nix generate -r requirements.txt
Traceback (most recent call last):
  File "/nix/store/5x10lhm39id91r1ah7piq9khwjb9r9m7-python2.7-pip2nix-0.2.0.dev1/bin/.pip2nix-wrapped", line 10, in <module>
    load_entry_point('pip2nix==0.2.0.dev1', 'console_scripts', 'pip2nix')()
  File "/nix/store/9x7s0nj92lhzyw8zp02nm3xkj3ca5dk1-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/9x7s0nj92lhzyw8zp02nm3xkj3ca5dk1-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 680, in main


    rv = self.invoke(ctx)
  File "/nix/store/9x7s0nj92lhzyw8zp02nm3xkj3ca5dk1-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/9x7s0nj92lhzyw8zp02nm3xkj3ca5dk1-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/9x7s0nj92lhzyw8zp02nm3xkj3ca5dk1-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/5x10lhm39id91r1ah7piq9khwjb9r9m7-python2.7-pip2nix-0.2.0.dev1/lib/python2.7/site-packages/pip2nix/cli.py", line 58, in generate
    config.find_and_load()
  File "/nix/store/5x10lhm39id91r1ah7piq9khwjb9r9m7-python2.7-pip2nix-0.2.0.dev1/lib/python2.7/site-packages/pip2nix/config.py", line 74, in find_and_load
    if self.load(path):
  File "/nix/store/5x10lhm39id91r1ah7piq9khwjb9r9m7-python2.7-pip2nix-0.2.0.dev1/lib/python2.7/site-packages/pip2nix/config.py", line 80, in load
    config = ConfigObj(path)
  File "/nix/store/sl61ycyash5hp7z4q2qj253cbw5js4gb-python2.7-configobj-5.0.6/lib/python2.7/site-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/nix/store/sl61ycyash5hp7z4q2qj253cbw5js4gb-python2.7-configobj-5.0.6/lib/python2.7/site-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 9.
```

**Comment by ktosiek** [comment]
It's not a problem with the requirements.txt. pip2nix tries to read the setup.cfg to see if there's any configuration for it there, and fails. I'll disable this, as ConfigObj (which I'm using for loading configuration) is pretty picky about syntax.

**Comment by tinkhaven** [comment]
That worked, thx!

**Comment by nttnhannho** [comment]
@tinkhaven could you please to tell me how to disable that?
