### ISSUE TITLE
Installation on ubuntu fails (tag v0.1.0)

### ISSUE THREAD

**Issue by plitzenberger** [nix-community/pip2nix#22]
ubuntu version:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

traceback:

```
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
Exception:
Traceback (most recent call last):
  File "/nix/store/5a4ixyqczpnpqfcwjl4mgkds28hn9cjm-python3-3.4.3/lib/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/nix/store/5a4ixyqczpnpqfcwjl4mgkds28hn9cjm-python3-3.4.3/bin/pip3' -> '/tmp/nix-build-python3.4-pip-7.1.0.drv-0/pip-ar46nwee-uninstall/nix/store/5a4ixyqczpnpqfcwjl4mgkds28hn9cjm-python3-3.4.3/bin/pip3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/commands/install.py", line 319, in run
    prefix=options.prefix_path,
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/nix/store/c84mvm6655k64aycq99j14caa8vxny0x-python-3.4.3-bootstrapped-pip-7.1.2/lib/python3.4/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/nix/store/5a4ixyqczpnpqfcwjl4mgkds28hn9cjm-python3-3.4.3/lib/python3.4/shutil.py", line 536, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/nix/store/5a4ixyqczpnpqfcwjl4mgkds28hn9cjm-python3-3.4.3/bin/pip3'
builder for ‘/nix/store/nwhjs6gq3axm2a8qrmwykm55av3w9v5x-python3.4-pip-7.1.0.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/yz131595h4whn9kib8vvql42kqxq6p03-python3.4-pip2nix-0.1.dev1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/yz131595h4whn9kib8vvql42kqxq6p03-python3.4-pip2nix-0.1.dev1.drv’ failed
```

**Comment by johbo** [comment]
Is this issue still relevant?

**Comment by johbo** [comment]
Housekeeping - I'll close this off, the issue does not seem to exist anymore.
