### ISSUE TITLE
ImportError: cannot import name 'WheelCache'

### ISSUE THREAD

**Issue by plitzenberger** [nix-community/pip2nix#23]
ubuntu version:

```
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

version:

```
commit a2263893465434966e9e0edd8f0e6566f4814f38
Author: Tomasz Kontusz <tomasz.kontusz@gmail.com>
Date:   Sat Nov 28 19:25:47 2015 +0100

    Removed shell.nix to test the new default.nix
```

installed with:

```
nix-env -f pip2nix/release.nix -iA pip2nix.python34
```

error when running:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip2nix generate -r development.txt
```

```
Traceback (most recent call last):
  File "/nix/store/9wsmn4z1jpypqxhg0kppqgfv7aw7adb9-python3.4-pip2nix-0.2.0.dev1/bin/.pip2nix-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/qyq486adshssj360kkmszlgvqhblypa6-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/qyq486adshssj360kkmszlgvqhblypa6-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/qyq486adshssj360kkmszlgvqhblypa6-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/qyq486adshssj360kkmszlgvqhblypa6-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/qyq486adshssj360kkmszlgvqhblypa6-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/9wsmn4z1jpypqxhg0kppqgfv7aw7adb9-python3.4-pip2nix-0.2.0.dev1/lib/python3.4/site-packages/pip2nix/cli.py", line 63, in generate
    from pip2nix.main import main
  File "/nix/store/9wsmn4z1jpypqxhg0kppqgfv7aw7adb9-python3.4-pip2nix-0.2.0.dev1/lib/python3.4/site-packages/pip2nix/main.py", line 9, in <module>
    from .generate import NixFreezeCommand
  File "/nix/store/9wsmn4z1jpypqxhg0kppqgfv7aw7adb9-python3.4-pip2nix-0.2.0.dev1/lib/python3.4/site-packages/pip2nix/generate.py", line 15, in <module>
    from pip.wheel import WheelCache
ImportError: cannot import name 'WheelCache'
```

**Comment by ktosiek** [comment]
What version of nixpkgs are you using? I'm not getting that error on d0e3cca (from unstable)

**Comment by plitzenberger** [comment]
where can I find this version? `.version-suffix` is `pre75772.9ee5a6b`

**Comment by johbo** [comment]
Is this still an issue?

**Comment by johbo** [comment]
Housekeeping - I'll close this off, the issue does not seem to exist anymore.
