### ISSUE TITLE
pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by teto** [nix-community/pip2nix#36]
While running nix-env -f $HOME/nixpkgs -iA python36Packages.pip2nix (nixpkgs being at revision 0376ccb7045401248dcd2b84f5fb4b8f1df61cb3), I encounter this error:

```copying build/lib/pip2nix/cli.py -> build/bdist.linux-x86_64/wheel/pip2nix
copying build/lib/pip2nix/egg_writer.py -> build/bdist.linux-x86_64/wheel/pip2nix
copying build/lib/pip2nix/__init__.py -> build/bdist.linux-x86_64/wheel/pip2nix
copying build/lib/pip2nix/confspec.ini -> build/bdist.linux-x86_64/wheel/pip2nix
copying build/lib/pip2nix/main.py -> build/bdist.linux-x86_64/wheel/pip2nix
running install_egg_info
running egg_info
Traceback (most recent call last):
  File "nix_run_setup.py", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 76, in <module>
    "tests_require.txt=pip2nix.egg_writer:write_arg"
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
    self.run_command('install')
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/gq5v7fk2fp1r632ywcicixkh09h8qigg-python3-3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 271, in run
    ep.require(installer=installer)
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2325, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pip 9.0.1 (/nix/store/4xdx3awzljv9gv52p3s3r5pccw35gz00-python3.6-bootstrapped-pip-9.0.1/lib/python3.6/site-packages), Requirement.parse('pip<9,>=8'))
builder for ‘/nix/store/ar5ywykbz9k9dhp1bd9rrh2lwsihcn4m-python3.6-pip2nix-0.3.0.drv’ failed with exit code 1
error: build of ‘/nix/store/ar5ywykbz9k9dhp1bd9rrh2lwsihcn4m-python3.6-pip2nix-0.3.0.drv’ failed
```
I wonder if pip2nix requirements can be the cause for it. Should install from source ?

**Comment by johbo** [comment]
Just noted the issue here, I've tried the same commit of nixpkgs, it's even flagged as broken there.

If you want to try, I would recommend to pick up a recent version of pip2nix, trying this way of installation should give you a working setup: https://github.com/johbo/pip2nix#installation

On my end I did recently change my approach of using it, since I switch python versions often I started to use nix-shell and run pip2nix inside of it:

```
johannes@dev-johbo: ~/wo/pip2nix master
$ nix-shell release.nix -A pip2nix.python36
```

And then I would `cd` into my project and use it somewhat like this:

```
[nix-shell:~/wbt/tryton/nix]$ pip2nix generate
```

**Comment by teto** [comment]
I now prefer to migrate projects to poetry toleverae poetry2nix so closing this.
