### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._internal.resolve'

### ISSUE THREAD

**Issue by ghost** [nix-community/pip2nix#58]
```sh
❯ pip2nix generate -r requirements.txt
Traceback (most recent call last):
  File "/private/tmp/delete/pip2nix/pip2nix/generate.py", line 23, in <module>
    from pip._internal.resolve import Resolver
ModuleNotFoundError: No module named 'pip._internal.resolve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/95/vltlhrln2wq6mc1f2ylwm96w0000gn/T/tmp.xr2So4kVRJ/bin/pip2nix"
, line 33, in <module>
    sys.exit(load_entry_point('pip2nix', 'console_scripts', 'pip2nix')())
  File "/nix/store/5kj7m135glz9k134s90jrv6g2wi9kv3a-python3.8-click-7.0/lib/python3.
8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/5kj7m135glz9k134s90jrv6g2wi9kv3a-python3.8-click-7.0/lib/python3.
8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/5kj7m135glz9k134s90jrv6g2wi9kv3a-python3.8-click-7.0/lib/python3.
8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/5kj7m135glz9k134s90jrv6g2wi9kv3a-python3.8-click-7.0/lib/python3.
8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/5kj7m135glz9k134s90jrv6g2wi9kv3a-python3.8-click-7.0/lib/python3.
8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/private/tmp/delete/pip2nix/pip2nix/cli.py", line 72, in generate
    from pip2nix.main import main
  File "/private/tmp/delete/pip2nix/pip2nix/main.py", line 9, in <module>
    from .generate import NixFreezeCommand
  File "/private/tmp/delete/pip2nix/pip2nix/generate.py", line 25, in <module>
    from pip._internal.legacy_resolve import Resolver
ModuleNotFoundError: No module named 'pip._internal.legacy_resolve'P
```

`requirements.txt`:
```txt
aiohttp
aiodns
beautifulsoup4
cchardet
dataclasses
elasticsearch
pysocks
pandas>=0.23.0
aiohttp_socks<=0.4.1
schedule
geopy
fake-useragent
googletransx
```

**Comment by datakurre** [comment]
Thanks. This due to continuing internal changes in pip, which this tool depends on.

Until I find time to update this, I have been using nixos-20.03-branch to run pip2nix myself. Using virtualenv with pip 19.3.1 should also work.

**Comment by Denommus** [comment]
An easy solution for me was to create the following overlay file in `~/.config/nixpkgs/overlays/pip.nix`:

```nix
self: super: {
  python36 = super.python36.override {
    packageOverrides = python-self: python-super: {
      pip = python-super.pip.overrideAttrs (oldAttrs: rec {
        version = "19.3.1";
        pname = "pip";
        name = "${pname}-${version}";
        patches = [];

        src = python-super.fetchPypi {
          inherit pname version;
          sha256 = "19vyfpkdj2m4svgza3kilk3h25gvm536p2l9d1v527h3q5v7s811";
        };
      });
    };
  };
}
```

**Comment by datakurre** [comment]
Nice. I've finally started using niv, so I do something alike

```
$ niv add nixos/nixpkgs -n nixos-20.03 -b nixos-20.03
$ niv add nix-community/pip2nix -n pip2nix

```

```nix
let

  sources = import ./nix/sources.nix;
  pip2nix = (import (sources.pip2nix + "/release.nix") {                                
    pkgs = import sources."nixos-20.03" {};                                           
  }).pip2nix;

in

mkShell {
  buildInputs = [
    pip2nix.python38
  ];
}
```
