### ISSUE TITLE
setuptools.build_meta.SetupRequirementsError

### ISSUE THREAD

**Issue by dvzubarev** [nix-community/pip2nix#63]
Hi, thanks for this package.
I'm on nixos-20.09 branch.
After `nix-shell release.nix -A pip2nix.python39` I try `pip2nix generate --output out.nix -r req.txt` and it results in an error.
My `req.txt` contains only `fairseq`.
I guess there should be `cython` and `numpy` available to build this package. How can I add them to the nix-shell?
```
Collecting fairseq
  Using cached fairseq-0.10.2.tar.gz (938 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /nix/store/h4hixxmfbsccyvwnnlgjc2sfcns0hfms-python3-3.9.0/bin/python3.9 /nix/store/y3hkqsfvf4kidvvqabr1vsl59r747hmb-python3.9-pip-20.1.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /run/user/1002/tmperfp9ec6
       cwd: /run/user/1002/pip-install-v_h_6mmm/fairseq
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "/run/user/1002/pip-build-env-mff9vsxa/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/run/user/1002/pip-build-env-mff9vsxa/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/run/user/1002/pip-build-env-mff9vsxa/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 60, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
```

**Comment by datakurre** [comment]
@dvzubarev I have had similar use cases where I need to have dependencies like cffi and postgres available. Usually having extra nix-shell -p with those packages in path (and PYTHONPATH) has worked.

But I managed to have cython with pip2nix in the same layer with
```
nix-shell -p "python39.withPackages(ps: [(import ./default.nix { pythonPackages = "python39Packages"; }) ps.cython])"
```

But then I run into separate issue with:

```
  ERROR: Command errored out with exit status 1:
   command: /nix/store/agcvlmzx6229wb6gwl6npgajxsvyjr4z-python3-3.9.1-env/bin/python /nix/store/q63qhrfm388qd23h9hv1kssgyk663lsi-python3-3.9.1-env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /run/user/33500/tmp0ee6gznt
       cwd: /run/user/33500/pip-install-6qizjofd/fairseq
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 60, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/nix/store/q63qhrfm388qd23h9hv1kssgyk663lsi-python3-3.9.1-env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/nix/store/q63qhrfm388qd23h9hv1kssgyk663lsi-python3-3.9.1-env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/q63qhrfm388qd23h9hv1kssgyk663lsi-python3-3.9.1-env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/run/user/33500/pip-build-env-bgbv13s_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  IsADirectoryError: [Errno 21] Is a directory: 'fairseq/examples'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /nix/store/agcvlmzx6229wb6gwl6npgajxsvyjr4z-python3-3.9.1-env/bin/python /nix/store/q63qhrfm388qd23h9hv1kssgyk663lsi-python3-3.9.1-env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /run/user/33500/tmp0ee6gznt Check the logs for full command output.
```

**Comment by datakurre** [comment]
@dvzubarev It seems that the source release at PYPI is broken, but a tarball from GitHub would work.

So, with req.txt
```
https://github.com/pytorch/fairseq/archive/53b781caad3d58cd7fefed80e17faf147d15da66.tar.gz
```

We can get out.nix with
```
nix-shell -p "python39.withPackages(ps: [(import ./default.nix { pythonPackages = "python39Packages"; }) ps.cython])"
pip2nix generate --output out.nix -r req.txt
```

BUT. Everything will fail short later, because torch has only binary releases at PyPI. out.nix will contain source distribution for version (0.1.2) which has chance for building.

Or is torch the same as pytorch, which is packaged in nixpkgs?

**Comment by datakurre** [comment]
With

```
let pkgs = import <nixpkgs> { };
in
let
  packageOverrides = pkgs.callPackage ./out.nix {};
  python = pkgs.python39.override {
    packageOverrides = self: super: (
      (packageOverrides self super) // {
      fairseq = (packageOverrides self super).fairseq.overridePythonAttrs(old: {
        nativeBuildInputs = [ pkgs.which ];
      });
      PyYAML = super.pyyaml;
      torch = super.pytorch;
      numpy = super.numpy;
      cffi = super.cffi;
    });
  };
  pythonWithPackages = python.withPackages(ps: [ ps.fairseq ]);
in
pkgs.mkShell {
  buildInputs = [
    pythonWithPackages
  ];
}
```

I got working nix-shell, but importing fairseq run into https://github.com/pytorch/pytorch/issues/48692

**Comment by datakurre** [comment]
NixOS 20.09 has too old pytorch for Python 3.9. I'll do one more try with
```
{ pkgs ? import (fetchTarball {                                                         
    url = "https://github.com/NixOS/nixpkgs/archive/d09f37cc24e4ec1a567f77e553a298158185182d.tar.gz";
    sha256 = "01k806m06fm41riak72xn3ryiy81rf09xklgqabil41r2kr7p98p";                    
  }) {}                                                                                 
}:                                                                                      
let                                                                                     
  packageOverrides = pkgs.callPackage ./out.nix {};                                     
  python = pkgs.python39.override {                                                     
    packageOverrides = self: super: (                                                   
      (packageOverrides self super) // {                                                
      fairseq = (packageOverrides self super).fairseq.overridePythonAttrs(old: {        
        nativeBuildInputs = [ pkgs.which ];                                             
      });                                                                               
      PyYAML = super.pyyaml;                                                            
      torch = super.pytorch;                                                            
      numpy = super.numpy;                                                              
      cffi = super.cffi;                                                                
    });                                                                                 
  };                                                                                    
  pythonWithPackages = python.withPackages(ps: [ ps.fairseq ]);                         
in                                                                                      
pkgs.mkShell {                                                                          
  buildInputs = [                                                                       
    pythonWithPackages                                                                  
  ];                                                                                    
} 
```

but that will take some time to build.

**Comment by dvzubarev** [comment]
Thank you very much for your help. I made significant progress of packaging my app. Torch was already built from nixpkgs in my setup, I just wanted to include other dependencies. Sorry for troubling.
