### ISSUE TITLE
Crashes with KeyError: 'lockfile' on package with build-system.requires = ["poetry"]

### ISSUE THREAD

**Issue by andersk** [nix-community/pip2nix#76]
The `django-scim2` package [declares  `build-system.requires`](https://github.com/15five/django-scim2/blob/0.17.2/pyproject.toml#L88-L89) on `poetry`, which [requires](https://github.com/python-poetry/poetry/blob/1.1.13/pyproject.toml#L36) `cachecontrol[filecache]`, which [requires](https://github.com/ionrock/cachecontrol/blob/v0.12.11/setup.py#L25) `lockfile`. This confuses `pip2nix` into crashing with `KeyError`.

```pytb
$ pip2nix generate django-scim2==0.17.2 
Collecting django-scim2==0.17.2
  Using cached django-scim2-0.17.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Django>=2.0
  Using cached Django-4.0.4-py3-none-any.whl (8.0 MB)
Collecting scim2-filter-parser==0.3.5
  Using cached scim2-filter-parser-0.3.5.tar.gz (19 kB)
…
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pytest-runner
  Using cached pytest_runner-6.0.0-py3-none-any.whl (7.2 kB)
Ignoring lockfile: markers 'extra == "filecache"' don't match your environment
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 138, in process_requirements
    requirement_set.requirements[req.name],
KeyError: 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/y3hkqsfvf4kidvvqabr1vsl59r747hmb-python3.9-pip-20.1.1/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 347, in run
    return requirement_set
  File "/nix/store/q3d21ys27dn3byyb9vsb55bcx5s68l8w-python3.9-contexter-0.1.4/lib/python3.9/site-packages/contexter.py", line 96, in __exit__
    reraise(exc)
  File "/nix/store/q3d21ys27dn3byyb9vsb55bcx5s68l8w-python3.9-contexter-0.1.4/lib/python3.9/site-packages/contexter.py", line 26, in reraise
    raise exc[1].with_traceback(exc[2])
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 346, in run
    requirement_set = self.super_run(options, args)
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 325, in super_run
    self.process_requirements(
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 145, in process_requirements
    requirement_set.requirements[req.name],
KeyError: 'lockfile'
WARNING: You are using pip version 20.1.1; however, version 22.0.4 is available.
You should consider upgrading via the '/nix/store/dpkf22k2cfj2cdydkwg86zd72kwmfdfy-python3-3.9.0-env/bin/python -m pip install --upgrade pip' command.
```

**Comment by datakurre** [comment]
Thanks for the reproducible report. 

Possibly some assumptions from the early days of pip2nix are no longer valid :thinking:
