### ISSUE TITLE
AssertionError: a direct req shouldn't have a parent and also, a non direct req should have a parent

### ISSUE THREAD

**Issue by andersk** [nix-community/pip2nix#77]
`pip2nix generate cairocffi==1.3.0 scim2-filter-parser==0.3.7` crashes with an `AssertionError` within

https://github.com/nix-community/pip2nix/blob/52541862542e953c3ccd475575ba7a51b06a1829/pip2nix/generate.py#L135

where `req` is `pytest-runner (from scim2-filter-parser==0.3.7)` and `req.is_direct` is `False`.

Both [`cairocffi`](https://github.com/Kozea/cairocffi/blob/v1.3.0/setup.cfg#L39) and [`scim2-filter-parser`](https://github.com/15five/scim2-filter-parser/blob/0.3.7/setup.py#L43) declare `setup_requires` on `pytest-runner`.

If I run this with only `cairocffi` or with only `scim2-filter-parser`, the same call happens where `req.is_direct` is `True` and it doesn’t crash.

```pytb
$ pip2nix generate cairocffi==1.3.0 scim2-filter-parser==0.3.7
Collecting cairocffi==1.3.0
  Using cached cairocffi-1.3.0.tar.gz (88 kB)
Collecting scim2-filter-parser==0.3.7
  Using cached scim2-filter-parser-0.3.7.tar.gz (20 kB)
Collecting cffi>=1.1.0
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Collecting sly==0.4
  Using cached sly-0.4.tar.gz (60 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/y3hkqsfvf4kidvvqabr1vsl59r747hmb-python3.9-pip-20.1.1/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 347, in run
    return requirement_set
  File "/nix/store/q3d21ys27dn3byyb9vsb55bcx5s68l8w-python3.9-contexter-0.1.4/lib/python3.9/site-packages/contexter.py", line 96, in __exit__
    reraise(exc)
  File "/nix/store/q3d21ys27dn3byyb9vsb55bcx5s68l8w-python3.9-contexter-0.1.4/lib/python3.9/site-packages/contexter.py", line 26, in reraise
    raise exc[1].with_traceback(exc[2])
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 346, in run
    requirement_set = self.super_run(options, args)
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 325, in super_run
    self.process_requirements(
  File "/nix/store/g01sq2a78df1fjxbf7zxxc6pm0fg3pf9-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/generate.py", line 135, in process_requirements
    resolver.resolve([req], check_supported_wheels=True)
  File "/nix/store/y3hkqsfvf4kidvvqabr1vsl59r747hmb-python3.9-pip-20.1.1/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 169, in resolve
    requirement_set.add_requirement(req)
  File "/nix/store/y3hkqsfvf4kidvvqabr1vsl59r747hmb-python3.9-pip-20.1.1/lib/python3.9/site-packages/pip/_internal/req/req_set.py", line 113, in add_requirement
    assert install_req.is_direct == (parent_req_name is None), (
AssertionError: a direct req shouldn't have a parent and also, a non direct req should have a parent
WARNING: You are using pip version 20.1.1; however, version 22.0.4 is available.
You should consider upgrading via the '/nix/store/dpkf22k2cfj2cdydkwg86zd72kwmfdfy-python3-3.9.0-env/bin/python -m pip install --upgrade pip' command.
```

**Comment by datakurre** [comment]
@andersk Please, if possible, try https://github.com/nix-community/pip2nix/tree/fix-use-resolved-pkg

I'm not the original author of pip2nix, but been mainly patching it some way or another to keep working on my use-cases (some years before the other options, and some I still don't know how to do with Poetry - like Plone site environments with hundred of exact package versions, some public, some private).

Keep in touch if you think pip2nix might still work for your use case. This will require rewrite sooner or later (maybe sooner) to work with the latest pip, but I am not hurrying it just for myself :sweat_smile:

**Comment by andersk** [comment]
`fix-use-resolved-pkg` seems to work, thanks.

(I work for Zulip, and I’m investigating options for migrating the [Zulip server](https://github.com/zulip/zulip) to Nix. I expect pip2nix can be made to work, but it’s possible that Poetry + poetry2nix may be a better fit. We’re also looking at mach-nix but I’m less convinced by that model. I’ll let you know what we settle on.)

**Comment by datakurre** [comment]
I agree that if poetry works for Zulip use case, poetry2nix is better option.

pip2nix exists still, because poetry was not option many years ago and and at least I have still many projects using it and then Plone sites…

Personally I am excited to hear Zulip considering Nix. 🚀
