### ISSUE TITLE
Error when launching generated file with nix-shell

### ISSUE THREAD

**Issue by mbledkowski** [nix-community/pip2nix#83]
I generated nix file for doccano and I get the following error when launching it using nix-shell command. 
```
shrinking RPATHs of ELF executables and libraries in /nix/store/qby8dsvaqdgsmxn91m793s5kbmqid8fn-python3.9-asgiref-3.6.0
setup.py:67: DeprecationWarning:

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html


  import numpy.distutils.command.sdist
strip is /nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0/bin/strip
stripping (with command strip and flags -S) in  /nix/store/qby8dsvaqdgsmxn91m793s5kbmqid8fn-python3.9-asgiref-3.6.0/lib
Traceback (most recent call last):
  File "setup.py", line 233, in generate_cython
    import Cython
ModuleNotFoundError: No module named 'Cython'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/numpy-1.24.1/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 479, in <module>
    setup_package()
  File "setup.py", line 458, in setup_package
    generate_cython()
  File "setup.py", line 240, in generate_cython
    raise OSError(msg) from e
OSError: Cython needs to be installed in Python as a module
error: builder for '/nix/store/2fqpafbp7bi2rx4n10xff83qmsc18i8h-python3.9-numpy-1.24.1.drv' failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "/build/numpy-1.24.1/nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >   File "setup.py", line 479, in <module>
       >     setup_package()
       >   File "setup.py", line 458, in setup_package
       >     generate_cython()
       >   File "setup.py", line 240, in generate_cython
       >     raise OSError(msg) from e
       > OSError: Cython needs to be installed in Python as a module
       For full logs, run 'nix log /nix/store/2fqpafbp7bi2rx4n10xff83qmsc18i8h-python3.9-numpy-1.24.1.drv'.
error: 1 dependencies of derivation '/nix/store/j077afg5m842yrjg37m0xh3f6mdm115g-python3.9-construct-2.10.68.drv' failed to build
error: 1 dependencies of derivation '/nix/store/27irzd7l2va0ch4gljsyjrfvrlv8rird-python3.9-orjson-3.8.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0gl1x0zlbid8pfk06gdbwxdwzzc6pk9f-python3.9-pillow-9.3.0.drv' failed to build
building '/nix/store/cm6xrqv2hy25y3jm0na8fx1xngjc9zsk-python3.9-certifi-2022.12.7.drv'...
error: 1 dependencies of derivation '/nix/store/wxr980pnadhqff36zvlidnnvyxc39hwf-python3.9-fastapi-0.85.2.drv' failed to build
building '/nix/store/vk2j2y6agbn9cg28lc6kjrzg9c4qwqsh-python3.9-gunicorn-20.1.0.drv'...
building '/nix/store/0zxdrl4cvd2l5vws9k2sza3vvj9fr07y-python3.9-idna-3.4.drv'...
building '/nix/store/8afpzg00xnc8ldg53fk66bh4d9x0pli9-python3.9-packaging-23.0.drv'...
error: 1 dependencies of derivation '/nix/store/3p6rl8lqnkmz91lh47mbmiqrypx7njsn-python3-3.9.16-env.drv' failed to build
```

**Comment by guillermofbriceno** [comment]
I don't know what you are trying package, but I was able to fix this by adding Cython to my `requirements.txt`, regenerating `python-packages.nix`, and adding  `self."Cython"` to the propagatedBuildInputs for numpy.
