### ISSUE TITLE
AttributeError: module 'validate' has no attribute 'force_list'

### ISSUE THREAD

**Issue by otavio** [nix-community/pip2nix#91]
Fail to parse the requirements, error is:

```
% nix run github:nix-community/pip2nix -- generate requirements.txt
Traceback (most recent call last):
  File "/nix/store/rwcgjzbf1g7ibz6yirkbpkyasmq92zli-python3.9-pip2nix-0.9.0.dev1/bin/..pip2nix-wrapped-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/dz6l6fbpyfj6l1j418yh5fi4bpgpvnaz-python3.9-click-7.1.2/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/dz6l6fbpyfj6l1j418yh5fi4bpgpvnaz-python3.9-click-7.1.2/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/dz6l6fbpyfj6l1j418yh5fi4bpgpvnaz-python3.9-click-7.1.2/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/dz6l6fbpyfj6l1j418yh5fi4bpgpvnaz-python3.9-click-7.1.2/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/dz6l6fbpyfj6l1j418yh5fi4bpgpvnaz-python3.9-click-7.1.2/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/rwcgjzbf1g7ibz6yirkbpkyasmq92zli-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/cli.py", line 70, in generate
    config.validate()
  File "/nix/store/rwcgjzbf1g7ibz6yirkbpkyasmq92zli-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/config.py", line 51, in validate
    errs = self.config.validate(validator, preserve_errors=True)
  File "/nix/store/glmq5lm9sgh76c17mky7xib6rrlskxb2-python3.10-configobj-5.0.8/lib/python3.10/site-packages/configobj/__init__.py", line 2310, in validate
    check = self.validate(validator, preserve_errors=preserve_errors, copy=copy, section=section[entry])
  File "/nix/store/glmq5lm9sgh76c17mky7xib6rrlskxb2-python3.10-configobj-5.0.8/lib/python3.10/site-packages/configobj/__init__.py", line 2265, in validate
    ret_true, ret_false = validate_entry(entry, configspec[entry], val,
  File "/nix/store/glmq5lm9sgh76c17mky7xib6rrlskxb2-python3.10-configobj-5.0.8/lib/python3.10/site-packages/configobj/__init__.py", line 2203, in validate_entry
    check = validator.check(spec,
  File "/nix/store/glmq5lm9sgh76c17mky7xib6rrlskxb2-python3.10-configobj-5.0.8/lib/python3.10/site-packages/configobj/validate.py", line 624, in check
    return self._check_value(value, fun_name, fun_args, fun_kwargs)
  File "/nix/store/glmq5lm9sgh76c17mky7xib6rrlskxb2-python3.10-configobj-5.0.8/lib/python3.10/site-packages/configobj/validate.py", line 656, in _check_value
    return fun(value, *fun_args, **fun_kwargs)
  File "/nix/store/rwcgjzbf1g7ibz6yirkbpkyasmq92zli-python3.9-pip2nix-0.9.0.dev1/lib/python3.9/site-packages/pip2nix/config.py", line 160, in requirements_list_validator
    value = validate.force_list(value, **kwargs)
AttributeError: module 'validate' has no attribute 'force_list'
```

**Comment by Kruziikrel13** [comment]
Also getting this error
